CREATE SCHEMA IF NOT EXISTS crypto_scheme;

SET search_path = crypto_scheme, public;

CREATE TABLE IF NOT EXISTS "User" (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Surename VARCHAR(50) NOT NULL,
    Passport VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Wallet" (
    WalletID SERIAL PRIMARY KEY,
    UserID INTEGER REFERENCES "User"(UserID) ON DELETE CASCADE,
    WalletNumber VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Coin" (
    CoinID SERIAL PRIMARY KEY,
    CoinName VARCHAR(50) NOT NULL UNIQUE,
    Price DECIMAL(15,2) NOT NULL CHECK (Price > 0),
    MCAP DECIMAL(20,2),
    Liquidity DECIMAL(15,2) CHECK (Liquidity >= 0),
    NumberOfHolders INTEGER,
    PercentOfTop30Holders DECIMAL(5,2) CHECK (PercentOfTop30Holders BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS "Exchange"(
    ExchangeID SERIAL PRIMARY KEY NOT NULL,
    NameExchange VARCHAR(50) UNIQUE NOT NULL,
    NumberOfUsers INTEGER
);

CREATE TABLE IF NOT EXISTS "Transaction" (
    TransactionID VARCHAR(64) PRIMARY KEY UNIQUE NOT NULL,
    WalletFirstID INTEGER REFERENCES "Wallet"(WalletID) ON DELETE CASCADE,
    WalletSecondID INTEGER REFERENCES "Wallet"(WalletID) ON DELETE CASCADE,
    CoinID INTEGER REFERENCES "Coin"(CoinID) ON DELETE CASCADE,
    ExchangeID INTEGER REFERENCES "Exchange"(ExchangeID) ON DELETE CASCADE,
    TimeTransaction TIMESTAMP NOT NULL,
    TransferredAmount DECIMAL(15,2) NOT NULL CHECK (TransferredAmount > 0)
);

CREATE TABLE IF NOT EXISTS "WalletCoins" (
    WalletID INTEGER NOT NULL,
    CoinID INTEGER NOT NULL,
    Quantity DECIMAL(15, 2) NOT NULL,
    PRIMARY KEY (WalletID, CoinID),
    FOREIGN KEY (WalletID) REFERENCES "Wallet"(WalletID) ON DELETE CASCADE,
    FOREIGN KEY (CoinID) REFERENCES "Coin"(CoinID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "CoinExchange" (
    ExchangeID INTEGER NOT NULL,
    CoinID INTEGER NOT NULL,
    PRIMARY KEY (ExchangeID, CoinID),
    FOREIGN KEY (ExchangeID) REFERENCES "Exchange"(ExchangeID) ON DELETE CASCADE,
    FOREIGN KEY (CoinID) REFERENCES "Coin"(CoinID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserExchange" (
    ExchangeID INTEGER NOT NULL,
    UserID INTEGER NOT NULL,
    PRIMARY KEY (ExchangeID, UserID),
    FOREIGN KEY (ExchangeID) REFERENCES "Exchange"(ExchangeID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES "User"(UserID) ON DELETE CASCADE
);